package mainPuzzle;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author matos
 */
public class JFramePuzzle extends javax.swing.JFrame {

	/**
	 * Creates new form NewJFrame1
	 */
	public JFramePuzzle() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jLabel2 = new javax.swing.JLabel();
		jComboBox4 = new javax.swing.JComboBox<>();
		jTextField1 = new javax.swing.JTextField();
		jComboBox5 = new javax.swing.JComboBox<>();
		jScrollPane4 = new javax.swing.JScrollPane();
		jTextPane2 = new javax.swing.JTextPane();
		jComboBox6 = new javax.swing.JComboBox<>();
		jComboBox7 = new javax.swing.JComboBox<>();
		jScrollPane5 = new javax.swing.JScrollPane();
		jTextPane3 = new javax.swing.JTextPane();
		jComboBox8 = new javax.swing.JComboBox<>();
		jComboBox9 = new javax.swing.JComboBox<>();
		jLabel3 = new javax.swing.JLabel();
		jButton1 = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();
		jLabel1 = new javax.swing.JLabel();
		jComboBox10 = new javax.swing.JComboBox<>();
		jComboBox1 = new javax.swing.JComboBox<>();
		jScrollPane3 = new javax.swing.JScrollPane();
		jTextPane1 = new javax.swing.JTextPane();
		jButton3 = new javax.swing.JButton();
		jComboBox2 = new javax.swing.JComboBox<>();
		jComboBox3 = new javax.swing.JComboBox<>();
		jLabel4 = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jLabel2.setText("ESTADO INICIAL");

		jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(
				new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", " " }));
		jComboBox4.setEnabled(false);
		jComboBox4.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jComboBox4ActionPerformed(evt);
			}
		});

		jTextField1.setEditable(false);

		jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(
				new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", " " }));
		jComboBox5.setEnabled(false);
		jComboBox5.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jComboBox5ActionPerformed(evt);
			}
		});

		jScrollPane4.setViewportView(jTextPane2);

		jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(
				new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", " " }));
		jComboBox6.setEnabled(false);
		jComboBox6.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jComboBox6ActionPerformed(evt);
			}
		});

		jComboBox7.setModel(new javax.swing.DefaultComboBoxModel<>(
				new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", " " }));
		jComboBox7.setEnabled(false);
		jComboBox7.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jComboBox7ActionPerformed(evt);
			}
		});

		jScrollPane5.setViewportView(jTextPane3);

		jComboBox8.setModel(new javax.swing.DefaultComboBoxModel<>(
				new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", " " }));
		jComboBox8.setEnabled(false);
		jComboBox8.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jComboBox8ActionPerformed(evt);
			}
		});

		jComboBox9.setModel(new javax.swing.DefaultComboBoxModel<>(
				new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", " " }));
		jComboBox9.setEnabled(false);
		jComboBox9.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jComboBox9ActionPerformed(evt);
			}
		});

		jLabel3.setText("Tem Solução?");

		jButton1.setText("Inserir");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jButton2.setText("Limpar");
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});

		jLabel1.setText("ESTADO FINAL");

		jComboBox10
				.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Escolha", "Randomico", "Inserir" }));
		jComboBox10.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jComboBox10ActionPerformed(evt);
			}
		});

		jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(
				new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", " " }));
		jComboBox1.setEnabled(false);
		jComboBox1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jComboBox1ActionPerformed(evt);
			}
		});

		jScrollPane3.setViewportView(jTextPane1);

		jButton3.setText("Sair");
		jButton3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton3ActionPerformed(evt);
			}
		});

		jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(
				new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", " " }));
		jComboBox2.setEnabled(false);
		jComboBox2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jComboBox2ActionPerformed(evt);
			}
		});

		jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(
				new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", " " }));
		jComboBox3.setEnabled(false);
		jComboBox3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jComboBox3ActionPerformed(evt);
			}
		});

		jLabel4.setText("DADOS");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
				.createSequentialGroup()
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(layout.createSequentialGroup()
								.addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
								.addGroup(javax.swing.GroupLayout.Alignment.LEADING,
										layout.createSequentialGroup().addGap(27, 27, 27).addComponent(
												jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 96,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGroup(layout.createSequentialGroup().addContainerGap()
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
												.addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 96,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(
														jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 96,
														javax.swing.GroupLayout.PREFERRED_SIZE))))
						.addGroup(layout.createSequentialGroup()
								.addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGroup(layout.createSequentialGroup()
								.addComponent(jComboBox7, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addComponent(jComboBox8, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addComponent(jComboBox9, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addComponent(jComboBox10, javax.swing.GroupLayout.PREFERRED_SIZE, 144,
								javax.swing.GroupLayout.PREFERRED_SIZE))
				.addGap(43, 43, 43)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jLabel2)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
										layout.createSequentialGroup().addComponent(jLabel3)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 87,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 196,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 196,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 196,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addComponent(jLabel1).addComponent(jLabel4))
				.addContainerGap(17, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addGap(20, 20, 20)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel3))
						.addGap(32, 32, 32)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 15,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jComboBox10, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
								.createSequentialGroup().addGap(30, 30, 30)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(jComboBox7, javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(jComboBox8, javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(jComboBox9, javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(jButton1).addGap(27, 27, 27).addComponent(jButton2).addGap(18, 18, 18)
								.addComponent(jButton3).addGap(41, 41, 41))
								.addGroup(layout.createSequentialGroup()
										.addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 70,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(18, 18, 18)
										.addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 15,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 70,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(5, 5, 5)
										.addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 15,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 106,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addContainerGap(21, Short.MAX_VALUE)))));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jComboBox4ActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jComboBox4ActionPerformed

	private void jComboBox5ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jComboBox5ActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jComboBox5ActionPerformed

	private void jComboBox6ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jComboBox6ActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jComboBox6ActionPerformed

	private void jComboBox7ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jComboBox7ActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jComboBox7ActionPerformed

	private void jComboBox8ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jComboBox8ActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jComboBox8ActionPerformed

	private void jComboBox9ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jComboBox9ActionPerformed

	}// GEN-LAST:event_jComboBox9ActionPerformed

	static int pos0;
	static int pos1;
	static int pos2;
	static int pos3;
	static int pos4;
	static int pos5;
	static int pos6;
	static int pos7;
	static int pos8;
	static int[][] stateInitial;

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed

		pos0 = Integer.parseInt(jComboBox1.getSelectedItem().toString());
		pos1 = Integer.parseInt(jComboBox2.getSelectedItem().toString());
		pos2 = Integer.parseInt(jComboBox3.getSelectedItem().toString());
		pos3 = Integer.parseInt(jComboBox4.getSelectedItem().toString());
		pos4 = Integer.parseInt(jComboBox5.getSelectedItem().toString());
		pos5 = Integer.parseInt(jComboBox6.getSelectedItem().toString());
		pos6 = Integer.parseInt(jComboBox7.getSelectedItem().toString());
		pos7 = Integer.parseInt(jComboBox8.getSelectedItem().toString());
		pos8 = Integer.parseInt(jComboBox9.getSelectedItem().toString());

		main();

	}// GEN-LAST:event_jButton1ActionPerformed

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton2ActionPerformed

		jTextField1.setText("");
		jTextPane1.setText("");
		jTextPane2.setText("");
		jTextPane3.setText("");

		jComboBox1.setEnabled(false);
		jComboBox2.setEnabled(false);
		jComboBox3.setEnabled(false);
		jComboBox4.setEnabled(false);
		jComboBox5.setEnabled(false);
		jComboBox6.setEnabled(false);
		jComboBox7.setEnabled(false);
		jComboBox8.setEnabled(false);
		jComboBox9.setEnabled(false);

		new JFramePuzzle().repaint();

		//
		// this.dispose();
		// new NewJFrame().setVisible(true);

	}// GEN-LAST:event_jButton2ActionPerformed

	private void jComboBox10ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jComboBox10ActionPerformed

		String comboBox = String.valueOf(jComboBox10.getSelectedItem());

		if (comboBox == "Inserir") {
			jComboBox1.setEnabled(true);
			jComboBox2.setEnabled(true);
			jComboBox3.setEnabled(true);
			jComboBox4.setEnabled(true);
			jComboBox5.setEnabled(true);
			jComboBox6.setEnabled(true);
			jComboBox7.setEnabled(true);
			jComboBox8.setEnabled(true);
			jComboBox9.setEnabled(true);
		}

	}// GEN-LAST:event_jComboBox10ActionPerformed

	private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jComboBox1ActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jComboBox1ActionPerformed

	private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton3ActionPerformed
		System.exit(0);
	}// GEN-LAST:event_jButton3ActionPerformed

	private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jComboBox2ActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jComboBox2ActionPerformed

	private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jComboBox3ActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jComboBox3ActionPerformed

	public void main() {

		try {
			long start = System.nanoTime();
			int[][] stateIni = staIni();

			String comboBox = String.valueOf(jComboBox10.getSelectedItem());
			System.out.println(comboBox);

			if (comboBox == "Randomico") {
				StatePuzzle state = new StatePuzzle(stateRandom());
				state.outPrint();

				jTextPane1.setText(state.toString());

				System.out.println("\n");

				if (state.isSolvable() == false) {
					jTextField1.setText("NÃO");
					System.out.println("Não há solução");
					System.exit(0);
				} else {
					jTextField1.setText("SIM");
				}
				visited.add(state);
				while (state.equalState(isGoal) == false) {
					addStateOrd(state);
					state = remove();
					visited.add(state);
				}
				List<StatePuzzle> result = new ArrayList<>();

				// Mostrar resultado

				while (state != null) {
					result.add(state);
					state = state.father;
				}
				Collections.reverse(result);

				for (StatePuzzle r : result) {
					r.outPrint();
					;
					System.out.println("");
					System.out.println("");

				}
				jTextPane2.setText(result.get(result.size() - 1) + "\n");

				long delay = System.nanoTime() - start;

				long timeExec = delay;
				jTextPane3.setText("Movimentos: " + result.size() + "\n" + "Profundidade: " + expand.size() + "\n"
						+ "Tempo de execução: " + timeExec + " nanosegundos");

			}

			if (comboBox == "Inserir") {
				StatePuzzle state = new StatePuzzle(staIni());
				state.outPrint();

				jTextPane1.setText(state.toString());

				System.out.println("\n");

				if (state.isSolvable() == false) {
					jTextField1.setText("NÃO");
					System.out.println("Não há solução");
					System.exit(0);
				} else {
					jTextField1.setText("SIM");
				}
				visited.add(state);
				while (state.equalState(isGoal) == false) {
					addStateOrd(state);
					state = remove();
					visited.add(state);
				}
				List<StatePuzzle> result = new ArrayList<>();

				// Mostrar resultado

				while (state != null) {
					result.add(state);
					state = state.father;
					result.remove(pos4);
				}
				Collections.reverse(result);
				for (StatePuzzle resultado : result) {
					resultado.outPrint();

					System.out.println("");
					System.out.println("");

				}
				jTextPane2.setText(result.get(result.size() - 1) + "\n");

				long delay = System.nanoTime() - start;

				long timeExec = delay;
				jTextPane3.setText("Movimentos: " + result.size() + "\n" + "Profundidade: " + expand.size() + "\n"
						+ "Tempo de execução: " + timeExec + " nanosegundos");

			}

		} catch (Exception e) {
			JOptionPane.showMessageDialog(null, e);
		}

	}

	static public int[][] staIni() {
		int[][] m = { { pos0, pos1, pos2 }, { pos3, pos4, pos5 }, { pos6, pos7, pos8 } };

		stateInitial = m;
		return stateInitial;

	}

	public static List<StatePuzzle> expand = new ArrayList<>();
	public final static List<StatePuzzle> visited = new ArrayList<>();
	public final static int[][] isGoal = { { 1, 2, 3 }, { 4, 5, 6 }, { 7, 8, 0 } };

	private static StatePuzzle remove() {
		Iterator<StatePuzzle> iterator = expand.iterator();
		while (iterator.hasNext()) {
			StatePuzzle next = iterator.next();
			if (visited.contains(next)) {
				iterator.remove();
				continue;
			}
			iterator.remove();
			return next;
		}
		return null;
	}

	private static void addStateOrd(StatePuzzle state) {
		for (StatePuzzle children : state.createChildren()) {
			boolean insert = false;
			for (int i = 0; i < expand.size(); i++) {
				if (children.value <= expand.get(i).value) {
					expand.add(i, children);
					insert = true;
					break;
				}
			}
			if (insert == false) {
				expand.add(children);
			}
		}
	}

	static public int[][] stateRandom() {
		List<Integer> valueList = new ArrayList<>();
		for (int i = 0; i < StatePuzzle.TOTAL_NUMEROS; i++) {
			valueList.add(i);
		}
		int[][] state = new int[StatePuzzle.TOTAL_LINHAS][StatePuzzle.TOTAL_COLUNAS];
		for (int i = 0; i < StatePuzzle.TOTAL_LINHAS; i++) {
			for (int j = 0; j < StatePuzzle.TOTAL_COLUNAS; j++) {
				int indexArray = new Random().nextInt(valueList.size());
				state[i][j] = valueList.get(indexArray);

				valueList.remove(indexArray);
			}
		}
		return state;
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(JFramePuzzle.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(JFramePuzzle.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(JFramePuzzle.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(JFramePuzzle.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		}
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new JFramePuzzle().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JButton jButton3;
	private javax.swing.JComboBox<String> jComboBox1;
	private javax.swing.JComboBox<String> jComboBox10;
	private javax.swing.JComboBox<String> jComboBox2;
	private javax.swing.JComboBox<String> jComboBox3;
	private javax.swing.JComboBox<String> jComboBox4;
	private javax.swing.JComboBox<String> jComboBox5;
	private javax.swing.JComboBox<String> jComboBox6;
	private javax.swing.JComboBox<String> jComboBox7;
	private javax.swing.JComboBox<String> jComboBox8;
	private javax.swing.JComboBox<String> jComboBox9;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JScrollPane jScrollPane3;
	private javax.swing.JScrollPane jScrollPane4;
	private javax.swing.JScrollPane jScrollPane5;
	private javax.swing.JTextField jTextField1;
	private javax.swing.JTextPane jTextPane1;
	private javax.swing.JTextPane jTextPane2;
	private javax.swing.JTextPane jTextPane3;
	// End of variables declaration//GEN-END:variables
}
